
export const GETALLDATA = "GETALLDATA";
export const GETDATALOADING = "GETDATALOADING";
export const GETDATAERROR = "GETDATAERROR";
export const GETALLDATATHUNK = "GETALLDATATHUNK";
export const GETDATALAPTOP = "GETDATALAPTOP";
export const GETSINGLEDATA = "GETSINGLEDATA";
export const CARTDATA = "CARTDATA";
export const UPDATEDCARTDATA = "UPDATEDCARTDATA";